### PR TITLE
Adding Peep for secure installation of Python Dependencies

### PR DESCRIPTION
**Pull request by safwanrahman**
Its better to use `peep` for securely install python dependencies.
More information can be found here: https://github.com/erikrose/peep

The installation process will be `./peep.sh install -r ./requirements/default.txt`

It also can be installed with `pip`. So there should not be any problem

### CODE REVIEW

**Comment by masnun** [comment]
Hey, 

Thanks a lot for the PR. BTW, is there any chance the hashes might be different based on OS/Platform?

**Comment by safwanrahman** [comment]
Yap. The hash can be different in different based OS if the package is from architecture-specific sources.
I dont think any of the dependencies we do use have architecture-specific sources, so there will little or no chance that their tarball have different hashes.

**Comment by safwanrahman** [comment]
If its a issue, I think its possible to add all the hashes that can be different in different OS. But if we deploy only in one environment, it will not be a big issue.

**Comment by masnun** [comment]
Merged, thank you!

**Pull request merged**
